### ISSUE TITLE
프레임워크 도입 및 fsd 패턴으로 아키텍쳐 설계

### ISSUE THREAD

**Issue by howyoujini** [gravidot/gravidot#1]
# 설명
**멀티터치 기반의 직관적 인터페이스로 아이디어를 연결하고, 실시간 협업을 지원하는 
브레인스토밍 및 마인드맵 서비스**를 구현하기 위해서 필요한 기술스택과 프레임워크 및 라이브러리를 설치해야합니다.

# Todos
- [x] Next typescript 로 설치
- [x] Turbopack 번들링 설치 - https://nextjs.org/docs/architecture/turbopack
- [x] node@20.18.0
- [x] Tailwind CSS
- [x] git
- [x] fsd 아키텍쳐 패턴 설계
- [x] branch ruleset 정의하기 - DO NOT PUSH MAIN

# 참고사항
## 기술 스택 선정 및 이유

- 플랫폼: `Web`
    - 데스크톱/태블릿/모바일 모든 플랫폼에서도 브라우저 앱으로 접근할 수 있기 때문에 선정했습니다.
    - **태블릿** 사용자 편의성을 지원한다면 오프라인에서도 사용가능한 `PWA` 도 지원할 수도 있기 때문에 선정했습니다.

- 언어: `typescript`
    - 자바스크립트의 정적 타입을 지원하기 때문에, 이후 타입스크립트로 `type` 과 `interface` **설계를 더욱 용이**하게 하고 더 쉽게 **타입 오류를 잡을 수도** 있기 때문에 선정했습니다. 휴먼에러나 타입에러를 런타임 시점까지 보내지 않고, 오류를 발견하는 사이클을 줄일 수 있습니다.

- 프레임워크: `Next v15.0.3` `React v18.0`
    - React 와 비슷한 생태계이기 때문에 Next 를 사용할 때 **러닝커브가 낮다고 판단**했습니다.
    - 바닐라 자바스크립트로 하기에는 명령형 UI이기 때문에 유지보수를 위해 **선언형 UI를 지원**하기 위해 선정했습니다.
    - **실시간 협업 페이지의 첫 로딩 속도가 중요**하다고 판단했기 때문에, SSR을 지원하는 Next 를 도입해보려고 합니다. ([**TTFB (Time to First Byte)를 약간 증가**시킬 수 있지만, 전체적인 FCP(First Contentful Paint)와 LCP(Largest Contentful Paint)가 개선됨](https://nextjs.org/conf/session/optimizing-lcp-partial-prerendering-deep-dive?utm_source))
    - 추가적으로 **브레인스토밍 템플릿을 지원**한다면 이런 정적 데이터는 **SSR를 통해 미리 렌더링**하여 클라이언트에 빠르게 제공할 수 있기 때문에 Next 를 도입하기로 결정했습니다.
    - Next 의 `Image` 컴포넌트를 사용해 **이미지 자동 최적화를** 지원받기 위해서 선정했습니다. 
    https://reactnext-central.xyz/blog/nextjs/image-component

- 그 외 라이브러리
    - `react-use-gesture` : 멀티제스쳐 인터페이스를 지원해줍니다.
    - `[superbase Realtime](https://supabase.com/docs/guides/realtime)`을 사용하면, 내부적으로 [[socket.io](http://socket.io/)](http://socket.io) 서버를 superbase 에서 따로 지원을 해주므로, `Vercel` 로 배포가 가능합니다.
        

- 번들링: [Turbopack](https://turbo.build/pack/docs) (Next.js 12 이후 실험적 도입)
    - Rust로 작성되어 훨씬 빠른 성능을 제공해줍니다.
    - dev 모드에서 더욱 빠른 핫 리로딩(Hot Reloading) 속도를 지원합니다.
    - Webpack과 비교해 더 낮은 리소스로 번들링할 수 있습니다.

- 테스트 도구: [Jest](https://jestjs.io/docs/getting-started) / [Playwright](https://playwright.dev/)
    - 타입스크립트 단위 테스트를 진행하기 위해 선정했습니다. https://jestjs.io/
    - `cypress` 보다는 **여러 장치와 브라우저**에서 자동화된 UI 테스트를 진행해보고자 선정했습니다.
    https://playwright.dev/

- 환경 버전 관리: `nvm use 20.18.0` = `node@20.18.0`
    - next 나 여러 다른 라이브러리가 node version 18+ 이상일 때, 지원해주기 때문입니다.

- 상태관리: `Zustand`
    - 단순하고 가벼운 (Redux 처럼 보일러플레이트가 많지 않음) API로 복잡한 상태를 효율적으로 관리할 수 있기 때문에 선정했습니다.
    - WebSocket 과 결합하기 쉽습니다. 상태와 비동기 데이터 처리를 직관적으로 연동할 수 있습니다.
    - Next 와 쉽게 통합 가능합니다.

- 스타일링: `Tailwind CSS`
    - 코드 수가 줄고 핵심 비지니스 로직에 스타일 코드가 침범하지 않는다는 장점을 활용할 수 있습니다.
    - 다크모드나 반응형 디자인을 쉽게 구현할 수 있습니다.
    - PostCSS와 같은 플러그인 기반의 툴과 잘 통합됩니다.
        - autoprefixer가 css코드에 vender prefixes를 자동으로 추가해주어 브라우저 호환성 관리 용이합니다.

- 배포: `Vercel`
    - [[socket.io](http://socket.io/)](http://socket.io) 를 활용하면, `Vercel` 을 사용할 수 없습니다. 이유는 로드밸런싱을 지원하지 않기 때문입니다. 하지만 superbase 의 realtime API 를 활용하면, Vercel 로 배포를 할 수 있기 때문에 (또, 새로운 여러 기술들을 공부하면서 써야하므로) 이를 활용하기로 결정을 하게 되었습니다.

- 형상관리도구: `git`
    - 파일과 폴더로 협업하기 위해 버전관리 시스템 선택했습니다.

- CI/CD: `Github Action`
    - 이미 github 을 사용하고 있어 github 과 `Github Action`의 통합으로 관리가 편하고, 무엇보다 간단하게 파이프라인을 작성할 수 있습니다.
    - 직접 commit 할 때마다 prettier, lint, test 를 수동으로 하지 않아도 되기 때문입니다.
    - 코드 변경 시 자동으로 테스트를 실행하여 기능이 깨지지 않도록 미리 테스트 해보려고 합니다.
    - 그리고 가능하다면, 여러 장치와 브라우저에서 자동화된 UI 테스트 실행해보면 좋을 것 같습니다.
    - `on` 스크립트에서 main 에 push/merge 되었을 때, 이벤트 시점을 정하여 자동배포할 수 있기 때문입니다.
