### ISSUE TITLE
펜툴/지우개 에디터 지원

### ISSUE THREAD

**Issue by howyoujini** [gravidot/gravidot#13]
# 설명
유저는 캔버스에 펜으로 그릴 수 있어야 한다.

# Todos
- [ ] 펜으로 그릴 수 있게 기능구현
- [ ] 그린 것을 저장할 수 있는 기능
- [ ] 지울 수 있는 기능
